CI: Add logic to trigger f3d-docker-image dispatch workflow (#2202)
f3d-docker-images needs to be manually dispatched when changing the timestamp.
This is cumbersome and require manual operation, this automatize this step.

A similar design may allow to enable VTK nightly builds again for android and wasm

Please note this REQUIRES a read/write PAT in a secract named: F3D_DOCKER_CI_DISPATCH to be able to run the action.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -702,10 +702,62 @@ jobs:
         vtk_version: ${{needs.default_versions.outputs.vtk_commit_sha}}
 
 #----------------------------------------------------------------------------
+# Check android/wasm docker images
+#----------------------------------------------------------------------------
+  check_docker_images:
+    needs: default_versions
+
+    runs-on: ubuntu-22.04
+
+    steps:
+
+    # {0} is needed to avoid exit on fail
+    - name: Check docker images exists
+      shell: bash {0}
+      working-directory: ${{github.workspace}}
+      run: |
+         docker manifest inspect ghcr.io/f3d-app/f3d-wasm:${{needs.default_versions.outputs.timestamp}}
+         res=$?
+         docker manifest inspect ghcr.io/f3d-app/f3d-android-armeabi-v7a:${{needs.default_versions.outputs.timestamp}}
+         [ $? -eq 0 ] && [ $res -eq 0 ] || res=$?
+         docker manifest inspect ghcr.io/f3d-app/f3d-android-arm64-v8a:${{needs.default_versions.outputs.timestamp}}
+         [ $? -eq 0 ] && [ $res -eq 0 ] || res=$?
+         docker manifest inspect ghcr.io/f3d-app/f3d-android-x86:${{needs.default_versions.outputs.timestamp}}
+         [ $? -eq 0 ] && [ $res -eq 0 ] || res=$?
+         docker manifest inspect ghcr.io/f3d-app/f3d-android-x86_64:${{needs.default_versions.outputs.timestamp}}
+         [ $? -eq 0 ] && [ $res -eq 0 ] || res=$?
+         echo "F3D_DOCKER_IMAGE_AVAILABLE=$res" >> $GITHUB_ENV
+
+    # This require a F3D_DOCKER_CI_DISPATCH secret contain a PAT with read and write admin access
+    - name: Trigger docker images build
+      env:
+          secret: ${{ secrets.F3D_DOCKER_CI_DISPATCH }}
+      if: ${{env.F3D_DOCKER_IMAGE_AVAILABLE == '1' && env.secret != '' }}
+      uses: convictional/trigger-workflow-and-wait@v1.6.5
+      with:
+        owner: f3d-app
+        repo: f3d-docker-images
+        github_token: ${{ secrets.F3D_DOCKER_CI_DISPATCH }}
+        workflow_file_name: build_docker_image.yml
+        wait_interval: 60
+        client_payload: '{"versions_file_url": "https://raw.githubusercontent.com/${{github.repository}}/${{github.ref}}/.github/workflows/versions.json"}'
+        propagate_failure: true
+        trigger_workflow: true
+        wait_workflow: true
+
+    - name: Error out when unable to build docker images
+      env:
+          secret: ${{ secrets.F3D_DOCKER_CI_DISPATCH }}
+      if: ${{env.F3D_DOCKER_IMAGE_AVAILABLE == '1' && env.secret == '' }}
+      uses: actions/github-script@v3
+      with:
+        script: core.setFailed('Could not generate missing docker images, reach out to a maintainer')
+
+#----------------------------------------------------------------------------
 # android: Check build of F3D for android
 #----------------------------------------------------------------------------
   android:
-    needs: [default_versions, detect_checkboxes]
+    needs: [default_versions, detect_checkboxes, check_docker_images]
     if: ${{ (contains(needs.detect_checkboxes.outputs.checked, 'Android CI')) || (github.ref == 'refs/heads/master') }}
 
     strategy:
@@ -734,7 +786,7 @@ jobs:
 # webassembly: Build webassembly artifacts
 #----------------------------------------------------------------------------
   webassembly:
-    needs: [default_versions, detect_checkboxes]
+    needs: [default_versions, detect_checkboxes, check_docker_images]
     if: ${{ (contains(needs.detect_checkboxes.outputs.checked, 'WASM CI')) || (github.ref == 'refs/heads/master') }}
 
     strategy:
